import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../core/localization/app_strings.dart';
import '../../core/providers.dart';
import '../../core/theme/app_theme.dart';
import '../../core/widgets/vibe_logo.dart';
import '../../models/models.dart';
import 'game_room_screen.dart';

class MatchSetupScreen extends ConsumerStatefulWidget { const MatchSetupScreen({super.key, required this.game}); final GameDescriptor game; @override ConsumerState<MatchSetupScreen> createState() => _MatchSetupScreenState(); }
class _MatchSetupScreenState extends ConsumerState<MatchSetupScreen> {
  late int players; String mode = 'casual'; bool busy = false; String? error;
  @override void initState() { super.initState(); players = widget.game.minPlayers; }
  @override Widget build(BuildContext context) { final strings = AppStrings(Localizations.localeOf(context)); return Scaffold(appBar: AppBar(title: Text(widget.game.name, style: const TextStyle(fontWeight: FontWeight.w900))), body: ListView(padding: const EdgeInsets.fromLTRB(22, 10, 22, 30), children: [Center(child: GameLogo(gameId: widget.game.id, accent: widget.game.accent, size: 100)), const SizedBox(height: 22), Text(strings.isPersian ? 'میز خودت را بساز' : 'Set up your table', style: Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight: FontWeight.w900)), const SizedBox(height: 8), Text(strings.isPersian ? 'حریف‌ها و قوانین را انتخاب کن؛ بعد وارد صف می‌شوی.' : 'Choose the room style and player count. We will find a fair table for you.', style: Theme.of(context).textTheme.bodyLarge?.copyWith(color: Theme.of(context).colorScheme.onSurfaceVariant)), const SizedBox(height: 28), Text(strings.isPersian ? 'نوع بازی' : 'Game mode', style: const TextStyle(fontWeight: FontWeight.w800)), const SizedBox(height: 10), SegmentedButton<String>(segments: [ButtonSegment(value: 'casual', label: Text(strings.casual), icon: const Icon(Icons.celebration_outlined)), ButtonSegment(value: 'ranked', label: Text(strings.ranked), icon: const Icon(Icons.emoji_events_outlined))], selected: {mode}, onSelectionChanged: (value) => setState(() => mode = value.first)), const SizedBox(height: 26), Text(strings.isPersian ? 'تعداد بازیکن' : 'Players at the table', style: const TextStyle(fontWeight: FontWeight.w800)), const SizedBox(height: 10), Wrap(spacing: 10, children: [for (var count = widget.game.minPlayers; count <= widget.game.maxPlayers; count++) ChoiceChip(label: Text('$count'), selected: players == count, onSelected: (_) => setState(() => players = count))]), if (widget.game.supportsTeams) Padding(padding: const EdgeInsets.only(top: 16), child: Container(padding: const EdgeInsets.all(14), decoration: BoxDecoration(color: AppTheme.mint.withOpacity(.1), borderRadius: BorderRadius.circular(16)), child: Row(children: [const Icon(Icons.groups_rounded, color: AppTheme.mint), const SizedBox(width: 10), Expanded(child: Text(strings.isPersian ? 'این بازی از تیم‌ها پشتیبانی می‌کند.' : 'This game supports balanced teams.', style: const TextStyle(fontWeight: FontWeight.w700)))]))), if (error != null) Padding(padding: const EdgeInsets.only(top: 16), child: Text(error!, style: TextStyle(color: Theme.of(context).colorScheme.error))), const SizedBox(height: 34), FilledButton.icon(onPressed: busy ? null : _find, icon: busy ? const SizedBox(width: 18, height: 18, child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white)) : const Icon(Icons.radar_rounded), label: Padding(padding: const EdgeInsets.symmetric(vertical: 5), child: Text(strings.findMatch))), const SizedBox(height: 10), OutlinedButton(onPressed: busy ? null : _instant, child: Text(strings.isPersian ? 'بازی فوری با بات' : 'Instant table with bots'))])); }
  Future<void> _find() async { setState(() { busy = true; error = null; }); try { final data = await ref.read(apiClientProvider).post('/matchmaking/join', data: {'gameId': widget.game.id, 'mode': mode, 'playerCount': players}) as Map; if (!mounted) return; await Navigator.of(context).push(MaterialPageRoute(builder: (_) => MatchQueueScreen(ticketId: data['id'] as String, game: widget.game))); } catch (e) { if (mounted) setState(() => error = e.toString()); } finally { if (mounted) setState(() => busy = false); } }
  Future<void> _instant() async { setState(() { busy = true; error = null; }); try { final data = await ref.read(apiClientProvider).post('/matches', data: {'gameId': widget.game.id, 'mode': 'casual', 'desiredPlayers': players}) as Map; if (mounted) await Navigator.of(context).push(MaterialPageRoute(builder: (_) => GameRoomScreen(matchId: data['id'] as String, game: widget.game))); } catch (e) { if (mounted) setState(() => error = e.toString()); } finally { if (mounted) setState(() => busy = false); } }
}

class MatchQueueScreen extends ConsumerStatefulWidget { const MatchQueueScreen({super.key, required this.ticketId, required this.game}); final String ticketId; final GameDescriptor game; @override ConsumerState<MatchQueueScreen> createState() => _MatchQueueScreenState(); }
class _MatchQueueScreenState extends ConsumerState<MatchQueueScreen> { Timer? timer; int seconds = 0; String? error; @override void initState() { super.initState(); timer = Timer.periodic(const Duration(seconds: 1), (_) => _poll()); }
  @override void dispose() { timer?.cancel(); super.dispose(); }
  Future<void> _poll() async { seconds += 1; try { final data = await ref.read(apiClientProvider).get('/matchmaking/${widget.ticketId}') as Map; if (data['status'] == 'cancelled' || data['status'] == 'expired') { timer?.cancel(); if (mounted) setState(() => error = 'Matchmaking ended. Please try again.'); return; } if (data['match'] is Map && mounted) { timer?.cancel(); final match = Map<String, dynamic>.from(data['match'] as Map); await Navigator.of(context).pushReplacement(MaterialPageRoute(builder: (_) => GameRoomScreen(matchId: match['id'] as String, game: widget.game))); } } catch (e) { if (mounted) setState(() => error = e.toString()); } }
  Future<void> _cancel() async { timer?.cancel(); try { await ref.read(apiClientProvider).delete('/matchmaking/leave', query: {'ticketId': widget.ticketId}); } finally { if (mounted) Navigator.of(context).pop(); } }
  @override Widget build(BuildContext context) { final strings = AppStrings(Localizations.localeOf(context)); return Scaffold(appBar: AppBar(leading: IconButton(onPressed: _cancel, icon: const Icon(Icons.close_rounded)), title: Text(strings.isPersian ? 'در حال پیدا کردن حریف' : 'Finding your table')), body: Center(child: Padding(padding: const EdgeInsets.all(32), child: Column(mainAxisSize: MainAxisSize.min, children: [GameLogo(gameId: widget.game.id, accent: widget.game.accent, size: 88), const SizedBox(height: 28), Text(strings.isPersian ? 'حریف مناسب را پیدا می‌کنیم…' : 'Finding a good match…', style: Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.w900)), const SizedBox(height: 10), Text(seconds < 15 ? (strings.isPersian ? 'بازیکن‌های واقعی در حال پیوستن هستند' : 'Real players are joining the table') : (strings.isPersian ? 'یک بات نامرئی و باهوش آماده می‌شود' : 'A human-like table bot is joining'), textAlign: TextAlign.center, style: TextStyle(color: Theme.of(context).colorScheme.onSurfaceVariant)), const SizedBox(height: 28), const SizedBox(width: 42, height: 42, child: CircularProgressIndicator(strokeWidth: 4)), const SizedBox(height: 30), Text('${seconds}s', style: const TextStyle(fontWeight: FontWeight.w900, fontSize: 18)), const SizedBox(height: 22), TextButton(onPressed: _cancel, child: Text(strings.cancel)), if (error != null) Text(error!, style: TextStyle(color: Theme.of(context).colorScheme.error))])))); }
}
