import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../core/localization/app_strings.dart';
import '../../core/providers.dart';
import '../../core/theme/app_theme.dart';
import '../../core/widgets/vibe_logo.dart';
import '../../models/models.dart';
import '../games/match_setup_screen.dart';
import 'home_provider.dart';

class HomeScreen extends ConsumerStatefulWidget { const HomeScreen({super.key}); @override ConsumerState<HomeScreen> createState() => _HomeScreenState(); }
class _HomeScreenState extends ConsumerState<HomeScreen> {
  String query = ''; GameCategory? category;
  @override Widget build(BuildContext context) { final strings = AppStrings(Localizations.localeOf(context)); final user = ref.watch(authProvider).value?.user; final games = ref.watch(gamesProvider).value ?? localGameCatalog; final filtered = games.where((game) => (category == null || game.category == category) && (query.isEmpty || game.name.toLowerCase().contains(query.toLowerCase()))).toList(); return RefreshIndicator(onRefresh: () async => ref.invalidate(gamesProvider), child: CustomScrollView(slivers: [SliverPadding(padding: const EdgeInsets.fromLTRB(20, 18, 20, 0), sliver: SliverToBoxAdapter(child: _Header(user: user))), SliverPadding(padding: const EdgeInsets.fromLTRB(20, 24, 20, 0), sliver: SliverToBoxAdapter(child: _HeroBanner(onTap: () => _open(context, games.first)))), SliverPadding(padding: const EdgeInsets.fromLTRB(20, 26, 20, 12), sliver: SliverToBoxAdapter(child: Text(strings.games, style: Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.w900)))), SliverToBoxAdapter(child: SizedBox(height: 42, child: ListView(scrollDirection: Axis.horizontal, padding: const EdgeInsets.symmetric(horizontal: 20), children: [ _FilterChip(label: strings.isPersian ? 'همه' : 'All', active: category == null, onTap: () => setState(() => category = null)), ...GameCategory.values.map((value) => _FilterChip(label: _categoryName(value, strings), active: category == value, onTap: () => setState(() => category = value))), ]))), SliverPadding(padding: const EdgeInsets.fromLTRB(20, 14, 20, 30), sliver: SliverToBoxAdapter(child: TextField(onChanged: (value) => setState(() => query = value), decoration: InputDecoration(hintText: strings.isPersian ? 'جست‌وجوی بازی' : 'Search games', prefixIcon: const Icon(Icons.search_rounded), suffixIcon: query.isEmpty ? null : IconButton(onPressed: () { setState(() => query = ''); }, icon: const Icon(Icons.close_rounded)))))), SliverPadding(padding: const EdgeInsets.symmetric(horizontal: 20), sliver: SliverGrid(delegate: SliverChildBuilderDelegate((context, index) { final game = filtered[index]; return _GameCard(game: game, onTap: () => _open(context, game)); }, childCount: filtered.length), gridDelegate: const SliverGridDelegateWithMaxCrossAxisExtent(maxCrossAxisExtent: 250, mainAxisExtent: 190, crossAxisSpacing: 14, mainAxisSpacing: 14))), if (filtered.isEmpty) SliverFillRemaining(hasScrollBody: false, child: Center(child: Text(strings.isPersian ? 'بازی‌ای پیدا نشد.' : 'No games found.'))), ])); }
  void _open(BuildContext context, GameDescriptor game) => Navigator.of(context).push(MaterialPageRoute(builder: (_) => MatchSetupScreen(game: game)));
  String _categoryName(GameCategory value, AppStrings strings) => switch (value) { GameCategory.board => strings.isPersian ? 'بردی' : 'Board', GameCategory.cards => strings.isPersian ? 'کارتی' : 'Cards', GameCategory.arcade => strings.isPersian ? 'آرکید' : 'Arcade', GameCategory.party => strings.isPersian ? 'دورهمی' : 'Party', GameCategory.sports => strings.isPersian ? 'ورزشی' : 'Sports' };
}

class _Header extends StatelessWidget { const _Header({required this.user}); final UserProfile? user; @override Widget build(BuildContext context) => Row(children: [const VibeLogo(compact: true), const SizedBox(width: 12), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('VibeTable', style: TextStyle(fontWeight: FontWeight.w900, fontSize: 18)), Text('Good vibes, great games', style: TextStyle(fontSize: 12, color: Colors.grey))])), BalancePill(value: user?.coins ?? 0, icon: Icons.circle, color: AppTheme.gold), const SizedBox(width: 8), CircleAvatar(radius: 19, backgroundColor: AppTheme.violet.withOpacity(.18), backgroundImage: user?.avatarUrl == null ? null : NetworkImage(user!.avatarUrl!), child: user?.avatarUrl == null ? Text((user?.displayName ?? 'V').substring(0, 1).toUpperCase(), style: const TextStyle(fontWeight: FontWeight.w900, color: AppTheme.violet)) : null)]); }

class _HeroBanner extends StatelessWidget { const _HeroBanner({required this.onTap}); final VoidCallback onTap; @override Widget build(BuildContext context) => InkWell(onTap: onTap, borderRadius: BorderRadius.circular(28), child: Container(height: 164, padding: const EdgeInsets.all(22), decoration: BoxDecoration(borderRadius: BorderRadius.circular(28), gradient: const LinearGradient(colors: [Color(0xFF2F236E), Color(0xFF7957F2)], begin: Alignment.topLeft, end: Alignment.bottomRight), boxShadow: [BoxShadow(color: AppTheme.violet.withOpacity(.25), blurRadius: 20, offset: const Offset(0, 10))]), child: Row(children: [Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [const Text('PLAY THE MOMENT', style: TextStyle(color: Color(0xFFD9CFFF), fontWeight: FontWeight.w800, letterSpacing: 1.2, fontSize: 11)), const SizedBox(height: 7), Text('Your table\nis waiting.', style: Theme.of(context).textTheme.headlineSmall?.copyWith(color: Colors.white, fontWeight: FontWeight.w900, height: 1.05)), const SizedBox(height: 12), Row(mainAxisSize: MainAxisSize.min, children: [const Text('Jump in', style: TextStyle(color: Colors.white, fontWeight: FontWeight.w800)), const SizedBox(width: 7), const Icon(Icons.arrow_forward_rounded, color: Colors.white, size: 18)])])), Transform.rotate(angle: -.16, child: const Icon(Icons.casino_rounded, size: 110, color: Color(0x55FFFFFF))) ])));
}

class _FilterChip extends StatelessWidget { const _FilterChip({required this.label, required this.active, required this.onTap}); final String label; final bool active; final VoidCallback onTap; @override Widget build(BuildContext context) => Padding(padding: const EdgeInsetsDirectional.only(end: 8), child: ChoiceChip(label: Text(label), selected: active, onSelected: (_) => onTap(), showCheckmark: false, padding: const EdgeInsets.symmetric(horizontal: 12), labelStyle: TextStyle(fontWeight: FontWeight.w700, color: active ? Colors.white : Theme.of(context).colorScheme.onSurfaceVariant), selectedColor: AppTheme.violet, backgroundColor: Theme.of(context).colorScheme.surface)); }

class _GameCard extends StatelessWidget { const _GameCard({required this.game, required this.onTap}); final GameDescriptor game; final VoidCallback onTap; @override Widget build(BuildContext context) => InkWell(onTap: onTap, borderRadius: BorderRadius.circular(24), child: Card(child: Padding(padding: const EdgeInsets.all(15), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [GameLogo(gameId: game.id, accent: game.accent, size: 54), const Spacer(), Text(game.name, maxLines: 1, overflow: TextOverflow.ellipsis, style: const TextStyle(fontWeight: FontWeight.w900, fontSize: 16)), const SizedBox(height: 4), Row(children: [Icon(Icons.people_alt_outlined, size: 14, color: Theme.of(context).colorScheme.onSurfaceVariant), const SizedBox(width: 4), Text('${game.minPlayers}-${game.maxPlayers}', style: TextStyle(fontSize: 12, color: Theme.of(context).colorScheme.onSurfaceVariant)), const Spacer(), Icon(Icons.arrow_forward_rounded, size: 17, color: Theme.of(context).colorScheme.primary)])]))));
}
