import { Action, asInt, GameEngine, GameId, GameOutcome, GamePlayer, GameState, IllegalMoveError, clone, nextTurn, randomInt, rotateTurn } from '../game.types';

function turnCheck(state: GameState, actorId: string): void {
  if (state.turnPlayerId !== actorId) throw new IllegalMoveError('It is not your turn.');
  if (state.winnerId || state.finished) throw new IllegalMoveError('This game has finished.');
}

export class FourInARowEngine implements GameEngine {
  readonly id: GameId = 'four_in_a_row';
  create(players: GamePlayer[]): GameState { return { board: Array.from({ length: 6 }, () => Array(7).fill(0)), turnIndex: 0, turnPlayerId: players[0].id, moveCount: 0, winnerId: null, finished: false }; }
  validate(state: GameState, actorId: string, action: Action, players: GamePlayer[]): void {
    turnCheck(state, actorId); if (action.type !== 'drop') throw new IllegalMoveError('Use the drop action.');
    const column = asInt(action.column, 'column', 0, 6); const board = state.board as number[][];
    if (board[0][column] !== 0) throw new IllegalMoveError('That column is full.');
    if (!players.some((p) => p.id === actorId)) throw new IllegalMoveError('You are not in this game.');
  }
  apply(state: GameState, actorId: string, action: Action, players: GamePlayer[]): GameState {
    this.validate(state, actorId, action, players); const next = clone(state); const board = next.board as number[][]; const column = action.column as number;
    let row = 5; while (row >= 0 && board[row][column] !== 0) row -= 1; board[row][column] = players.findIndex((p) => p.id === actorId) + 1; next.moveCount = Number(next.moveCount) + 1;
    if (this.hasLine(board, row, column, board[row][column])) { next.winnerId = actorId; next.finished = true; }
    else if (Number(next.moveCount) === 42) { next.draw = true; next.finished = true; } else rotateTurn(next, players);
    return next;
  }
  outcome(state: GameState, players: GamePlayer[]): GameOutcome { const winner = typeof state.winnerId === 'string' ? state.winnerId : ''; return { finished: Boolean(state.finished), winnerIds: winner ? [winner] : [], loserIds: winner ? players.filter((p) => p.id !== winner).map((p) => p.id) : [], draw: Boolean(state.draw) }; }
  botAction(state: GameState, botId: string): Action { const board = state.board as number[][]; const legal = Array.from({ length: 7 }, (_, column) => column).filter((column) => board[0][column] === 0); return { type: 'drop', column: legal[randomInt(legal.length)] ?? 0 }; }
  private hasLine(board: number[][], row: number, col: number, value: number): boolean { return [[1, 0], [0, 1], [1, 1], [1, -1]].some(([dr, dc]) => 1 + this.count(board, row, col, dr, dc, value) + this.count(board, row, col, -dr, -dc, value) >= 4); }
  private count(board: number[][], row: number, col: number, dr: number, dc: number, value: number): number { let count = 0; let r = row + dr; let c = col + dc; while (r >= 0 && r < 6 && c >= 0 && c < 7 && board[r][c] === value) { count += 1; r += dr; c += dc; } return count; }
}

export class MancalaEngine implements GameEngine {
  readonly id: GameId = 'mancala';
  create(players: GamePlayer[]): GameState { return { pits: [Array(6).fill(4), Array(6).fill(4)], stores: [0, 0], turnIndex: 0, turnPlayerId: players[0].id, finished: false, winnerId: null }; }
  validate(state: GameState, actorId: string, action: Action, players: GamePlayer[]): void { turnCheck(state, actorId); if (action.type !== 'sow') throw new IllegalMoveError('Use the sow action.'); const pit = asInt(action.pit, 'pit', 0, 5); const side = players.findIndex((p) => p.id === actorId); if ((state.pits as number[][])[side][pit] < 1) throw new IllegalMoveError('That pit is empty.'); }
  apply(state: GameState, actorId: string, action: Action, players: GamePlayer[]): GameState { this.validate(state, actorId, action, players); const next = clone(state); const side = players.findIndex((p) => p.id === actorId); const pits = next.pits as number[][]; const stores = next.stores as number[]; let stones = pits[side][action.pit as number]; pits[side][action.pit as number] = 0; let currentSide = side; let index = action.pit as number; let lastStore = false;
    while (stones > 0) { index += 1; if (index === 6) { if (currentSide === side) { stores[side] += 1; stones -= 1; lastStore = stones === 0; } index = -1; currentSide = currentSide === 0 ? 1 : 0; } else { pits[currentSide][index] += 1; stones -= 1; lastStore = false; if (stones === 0 && currentSide === side && pits[currentSide][index] === 1 && pits[1 - side][5 - index] > 0) { stores[side] += pits[1 - side][5 - index] + 1; pits[1 - side][5 - index] = 0; pits[side][index] = 0; } } }
    const sideEmpty = pits[side].every((stone) => stone === 0); const otherEmpty = pits[1 - side].every((stone) => stone === 0); if (sideEmpty || otherEmpty) { for (let s = 0; s < 2; s += 1) { stores[s] += pits[s].reduce((a, b) => a + b, 0); pits[s].fill(0); } next.finished = true; next.winnerId = stores[0] === stores[1] ? null : players[stores[0] > stores[1] ? 0 : 1].id; next.draw = stores[0] === stores[1]; } else if (!lastStore) rotateTurn(next, players); return next; }
  outcome(state: GameState, players: GamePlayer[]): GameOutcome { const winner = typeof state.winnerId === 'string' ? state.winnerId : ''; return { finished: Boolean(state.finished), winnerIds: winner ? [winner] : [], loserIds: winner ? players.filter((p) => p.id !== winner).map((p) => p.id) : [], draw: Boolean(state.draw) }; }
  botAction(state: GameState, botId: string, players: GamePlayer[]): Action { const side = players.findIndex((p) => p.id === botId); const legal = (state.pits as number[][])[side].map((stone, pit) => stone > 0 ? pit : -1).filter((pit) => pit >= 0); return { type: 'sow', pit: legal[randomInt(legal.length)] ?? 0 }; }
}

export class CheckersEngine implements GameEngine {
  readonly id: GameId = 'checkers';
  create(players: GamePlayer[]): GameState { const board: (string | null)[][] = Array.from({ length: 8 }, () => Array(8).fill(null)); for (let r = 0; r < 3; r += 1) for (let c = 0; c < 8; c += 1) if ((r + c) % 2 === 1) board[r][c] = 'b'; for (let r = 5; r < 8; r += 1) for (let c = 0; c < 8; c += 1) if ((r + c) % 2 === 1) board[r][c] = 'r'; return { board, turnIndex: 0, turnPlayerId: players[0].id, forcedFrom: null, winnerId: null, finished: false }; }
  validate(state: GameState, actorId: string, action: Action, players: GamePlayer[]): void { turnCheck(state, actorId); if (action.type !== 'move') throw new IllegalMoveError('Use the move action.'); const from = this.square(action.fromRow, action.fromCol); const to = this.square(action.toRow, action.toCol); const board = state.board as (string | null)[][]; const piece = board[from.r][from.c]; const color = players.findIndex((p) => p.id === actorId) === 0 ? 'r' : 'b'; if (!piece || piece.toLowerCase() !== color) throw new IllegalMoveError('That is not your piece.'); if (state.forcedFrom && (state.forcedFrom as { r: number; c: number }).r !== from.r) throw new IllegalMoveError('You must continue the capture.'); if (state.forcedFrom && (state.forcedFrom as { r: number; c: number }).c !== from.c) throw new IllegalMoveError('You must continue the capture.'); if (board[to.r][to.c]) throw new IllegalMoveError('The destination is occupied.'); const moves = this.movesFor(board, from.r, from.c, piece, this.hasAnyCapture(board, color)); if (!moves.some((m) => m.r === to.r && m.c === to.c)) throw new IllegalMoveError('That move is not legal.'); }
  apply(state: GameState, actorId: string, action: Action, players: GamePlayer[]): GameState { this.validate(state, actorId, action, players); const next = clone(state); const board = next.board as (string | null)[][]; const fr = action.fromRow as number; const fc = action.fromCol as number; const tr = action.toRow as number; const tc = action.toCol as number; let piece = board[fr][fc] as string; board[fr][fc] = null; const isCapture = Math.abs(tr - fr) === 2; if (isCapture) board[(fr + tr) / 2][(fc + tc) / 2] = null; if (piece === 'r' && tr === 0) piece = 'R'; if (piece === 'b' && tr === 7) piece = 'B'; board[tr][tc] = piece; const color = players.findIndex((p) => p.id === actorId) === 0 ? 'r' : 'b'; const moreCapture = isCapture && this.movesFor(board, tr, tc, piece, true).some((m) => m.r !== tr || m.c !== tc); if (moreCapture) { next.forcedFrom = { r: tr, c: tc }; } else { next.forcedFrom = null; rotateTurn(next, players); } const nextColor = players.findIndex((p) => p.id === next.turnPlayerId) === 0 ? 'r' : 'b'; if (!this.hasPieces(board, nextColor) || !this.hasAnyLegalMove(board, nextColor)) { next.finished = true; next.winnerId = actorId; } void color; return next; }
  outcome(state: GameState, players: GamePlayer[]): GameOutcome { const winner = typeof state.winnerId === 'string' ? state.winnerId : ''; return { finished: Boolean(state.finished), winnerIds: winner ? [winner] : [], loserIds: winner ? players.filter((p) => p.id !== winner).map((p) => p.id) : [], draw: false }; }
  botAction(state: GameState, botId: string, players: GamePlayer[]): Action { const board = state.board as (string | null)[][]; const color = players.findIndex((p) => p.id === botId) === 0 ? 'r' : 'b'; const moves: Action[] = []; for (let r = 0; r < 8; r += 1) for (let c = 0; c < 8; c += 1) { const piece = board[r][c]; if (piece?.toLowerCase() === color) for (const move of this.movesFor(board, r, c, piece, this.hasAnyCapture(board, color))) moves.push({ type: 'move', fromRow: r, fromCol: c, toRow: move.r, toCol: move.c }); } return moves[randomInt(moves.length)] ?? { type: 'move', fromRow: 0, fromCol: 0, toRow: 0, toCol: 0 }; }
  private square(r: unknown, c: unknown): { r: number; c: number } { return { r: asInt(r, 'row', 0, 7), c: asInt(c, 'column', 0, 7) }; }
  private movesFor(board: (string | null)[][], r: number, c: number, piece: string, captureOnly: boolean): Array<{ r: number; c: number }> { const directions = piece.toUpperCase() === piece ? [[1, 1], [1, -1], [-1, 1], [-1, -1]] : piece === 'r' ? [[-1, 1], [-1, -1]] : [[1, 1], [1, -1]]; const moves: Array<{ r: number; c: number }> = []; for (const [dr, dc] of directions) { const nr = r + dr; const nc = c + dc; const jr = r + dr * 2; const jc = c + dc * 2; if (!captureOnly && this.inside(nr, nc) && !board[nr][nc]) moves.push({ r: nr, c: nc }); if (this.inside(jr, jc) && board[nr]?.[nc] && board[nr][nc]?.toLowerCase() !== piece.toLowerCase() && !board[jr][jc]) moves.push({ r: jr, c: jc }); } return moves; }
  private hasAnyCapture(board: (string | null)[][], color: string): boolean { for (let r = 0; r < 8; r += 1) for (let c = 0; c < 8; c += 1) { const piece = board[r][c]; if (piece?.toLowerCase() === color && this.movesFor(board, r, c, piece, true).some((m) => Math.abs(m.r - r) === 2)) return true; } return false; }
  private hasAnyLegalMove(board: (string | null)[][], color: string): boolean { const capture = this.hasAnyCapture(board, color); for (let r = 0; r < 8; r += 1) for (let c = 0; c < 8; c += 1) { const piece = board[r][c]; if (piece?.toLowerCase() === color && this.movesFor(board, r, c, piece, capture).length) return true; } return false; }
  private hasPieces(board: (string | null)[][], color: string): boolean { return board.some((row) => row.some((piece) => piece?.toLowerCase() === color)); }
  private inside(r: number, c: number): boolean { return r >= 0 && r < 8 && c >= 0 && c < 8; }
}

interface ChessState extends GameState { board: (string | null)[][]; turnIndex: number; turnPlayerId: string; castling: { K: boolean; Q: boolean; k: boolean; q: boolean }; enPassant: { r: number; c: number } | null; winnerId: string | null; finished: boolean; draw?: boolean; }

export class ChessEngine implements GameEngine {
  readonly id: GameId = 'chess';
  create(players: GamePlayer[]): ChessState { const board: (string | null)[][] = [['r','n','b','q','k','b','n','r'], Array(8).fill('p'), ...Array.from({ length: 4 }, () => Array(8).fill(null)), Array(8).fill('P'), ['R','N','B','Q','K','B','N','R']]; return { board, turnIndex: 0, turnPlayerId: players[0].id, castling: { K: true, Q: true, k: true, q: true }, enPassant: null, winnerId: null, finished: false }; }
  validate(state: GameState, actorId: string, action: Action, players: GamePlayer[]): void { const s = state as ChessState; turnCheck(s, actorId); if (action.type !== 'move') throw new IllegalMoveError('Use the move action.'); const from = this.coord(action.fromRow, action.fromCol); const to = this.coord(action.toRow, action.toCol); const piece = s.board[from.r][from.c]; const color = players.findIndex((p) => p.id === actorId) === 0 ? 'w' : 'b'; if (!piece || this.color(piece) !== color) throw new IllegalMoveError('That is not your piece.'); const moves = this.legalMoves(s, color); if (!moves.some((move) => move.fr === from.r && move.fc === from.c && move.tr === to.r && move.tc === to.c)) throw new IllegalMoveError('That move would be illegal.'); }
  apply(state: GameState, actorId: string, action: Action, players: GamePlayer[]): ChessState { this.validate(state, actorId, action, players); const s = clone(state) as ChessState; const fr = action.fromRow as number; const fc = action.fromCol as number; const tr = action.toRow as number; const tc = action.toCol as number; const piece = s.board[fr][fc] as string; const captured = s.board[tr][tc]; s.board[fr][fc] = null; if ((piece === 'P' || piece === 'p') && s.enPassant && tr === s.enPassant.r && tc === s.enPassant.c) s.board[piece === 'P' ? tr + 1 : tr - 1][tc] = null; s.board[tr][tc] = piece; if (piece === 'K') { s.castling.K = false; s.castling.Q = false; if (fc === 4 && tc === 6) { s.board[7][7] = null; s.board[7][5] = 'R'; } if (fc === 4 && tc === 2) { s.board[7][0] = null; s.board[7][3] = 'R'; } } if (piece === 'k') { s.castling.k = false; s.castling.q = false; if (fc === 4 && tc === 6) { s.board[0][7] = null; s.board[0][5] = 'r'; } if (fc === 4 && tc === 2) { s.board[0][0] = null; s.board[0][3] = 'r'; } } if (piece === 'R' && fr === 7 && fc === 0) s.castling.Q = false; if (piece === 'R' && fr === 7 && fc === 7) s.castling.K = false; if (piece === 'r' && fr === 0 && fc === 0) s.castling.q = false; if (piece === 'r' && fr === 0 && fc === 7) s.castling.k = false; if (captured === 'R' && tr === 7 && tc === 0) s.castling.Q = false; if (captured === 'R' && tr === 7 && tc === 7) s.castling.K = false; if (captured === 'r' && tr === 0 && tc === 0) s.castling.q = false; if (captured === 'r' && tr === 0 && tc === 7) s.castling.k = false; if ((piece === 'P' || piece === 'p') && Math.abs(tr - fr) === 2) s.enPassant = { r: (tr + fr) / 2, c: fc }; else s.enPassant = null; if ((piece === 'P' && tr === 0) || (piece === 'p' && tr === 7)) { const promotion = typeof action.promotion === 'string' && ['q','r','b','n'].includes(action.promotion as string) ? action.promotion as string : 'q'; s.board[tr][tc] = piece === 'P' ? promotion.toUpperCase() : promotion; } const nextColor = players.findIndex((p) => p.id === actorId) === 0 ? 'b' : 'w'; rotateTurn(s, players); const legal = this.legalMoves(s, nextColor); const inCheck = this.inCheck(s.board, nextColor); if (!legal.length) { s.finished = true; if (inCheck) s.winnerId = actorId; else s.draw = true; } return s; }
  outcome(state: GameState, players: GamePlayer[]): GameOutcome { const winner = typeof state.winnerId === 'string' ? state.winnerId : ''; return { finished: Boolean(state.finished), winnerIds: winner ? [winner] : [], loserIds: winner ? players.filter((p) => p.id !== winner).map((p) => p.id) : [], draw: Boolean(state.draw) }; }
  botAction(state: GameState, botId: string, players: GamePlayer[]): Action { const color = players.findIndex((p) => p.id === botId) === 0 ? 'w' : 'b'; const moves = this.legalMoves(state as ChessState, color); const move = moves[randomInt(moves.length)]; return move ? { type: 'move', fromRow: move.fr, fromCol: move.fc, toRow: move.tr, toCol: move.tc } : { type: 'move', fromRow: 0, fromCol: 0, toRow: 0, toCol: 0 }; }
  private coord(r: unknown, c: unknown) { return { r: asInt(r, 'row', 0, 7), c: asInt(c, 'column', 0, 7) }; }
  private color(piece: string): 'w' | 'b' { return piece === piece.toUpperCase() ? 'w' : 'b'; }
  private legalMoves(s: ChessState, color: 'w' | 'b'): Array<{ fr: number; fc: number; tr: number; tc: number }> { const pseudo = this.pseudoMoves(s, color); return pseudo.filter((move) => { const copy = clone(s); this.makeForCheck(copy, move); return !this.inCheck(copy.board, color); }); }
  private pseudoMoves(s: ChessState, color: 'w' | 'b') { const moves: Array<{ fr: number; fc: number; tr: number; tc: number }> = []; for (let r = 0; r < 8; r += 1) for (let c = 0; c < 8; c += 1) { const piece = s.board[r][c]; if (!piece || this.color(piece) !== color) continue; const lower = piece.toLowerCase(); if (lower === 'p') { const dir = color === 'w' ? -1 : 1; const start = color === 'w' ? 6 : 1; if (this.inside(r + dir, c) && !s.board[r + dir][c]) { moves.push({ fr: r, fc: c, tr: r + dir, tc: c }); if (r === start && !s.board[r + 2 * dir][c]) moves.push({ fr: r, fc: c, tr: r + 2 * dir, tc: c }); } for (const dc of [-1, 1]) if (this.inside(r + dir, c + dc) && ((s.board[r + dir][c + dc] && this.color(s.board[r + dir][c + dc] as string) !== color) || (s.enPassant?.r === r + dir && s.enPassant.c === c + dc))) moves.push({ fr: r, fc: c, tr: r + dir, tc: c + dc }); } else if (lower === 'n') { for (const [dr, dc] of [[-2,-1],[-2,1],[-1,-2],[-1,2],[1,-2],[1,2],[2,-1],[2,1]]) this.addIfValid(s, moves, r, c, r + dr, c + dc, color); } else if (lower === 'k') { for (const [dr, dc] of [[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1]]) this.addIfValid(s, moves, r, c, r + dr, c + dc, color); const row = color === 'w' ? 7 : 0; if (r === row && c === 4 && !this.inCheck(s.board, color)) { const rights = color === 'w' ? s.castling : { K: s.castling.k, Q: s.castling.q }; if (rights.K && !s.board[row][5] && !s.board[row][6] && !this.attacked(s.board, row, 5, color === 'w' ? 'b' : 'w') && !this.attacked(s.board, row, 6, color === 'w' ? 'b' : 'w')) moves.push({ fr: row, fc: 4, tr: row, tc: 6 }); if (rights.Q && !s.board[row][1] && !s.board[row][2] && !s.board[row][3] && !this.attacked(s.board, row, 3, color === 'w' ? 'b' : 'w') && !this.attacked(s.board, row, 2, color === 'w' ? 'b' : 'w')) moves.push({ fr: row, fc: 4, tr: row, tc: 2 }); } } else { const directions = lower === 'b' ? [[1,1],[1,-1],[-1,1],[-1,-1]] : lower === 'r' ? [[1,0],[-1,0],[0,1],[0,-1]] : [[1,1],[1,-1],[-1,1],[-1,-1],[1,0],[-1,0],[0,1],[0,-1]]; for (const [dr, dc] of directions) { let nr = r + dr; let nc = c + dc; while (this.inside(nr, nc)) { if (!this.addIfValid(s, moves, r, c, nr, nc, color)) break; if (s.board[nr][nc]) break; nr += dr; nc += dc; } } } } return moves; }
  private addIfValid(s: ChessState, moves: Array<{ fr: number; fc: number; tr: number; tc: number }>, fr: number, fc: number, tr: number, tc: number, color: 'w' | 'b'): boolean { if (!this.inside(tr, tc)) return false; const target = s.board[tr][tc]; if (!target || this.color(target) !== color) moves.push({ fr, fc, tr, tc }); return !target; }
  private makeForCheck(s: ChessState, move: { fr: number; fc: number; tr: number; tc: number }): void { const piece = s.board[move.fr][move.fc]; s.board[move.tr][move.tc] = piece; s.board[move.fr][move.fc] = null; }
  private inCheck(board: (string | null)[][], color: 'w' | 'b'): boolean { let kr = -1; let kc = -1; for (let r = 0; r < 8; r += 1) for (let c = 0; c < 8; c += 1) if (board[r][c] === (color === 'w' ? 'K' : 'k')) { kr = r; kc = c; } return kr < 0 || this.attacked(board, kr, kc, color === 'w' ? 'b' : 'w'); }
  private attacked(board: (string | null)[][], r: number, c: number, by: 'w' | 'b'): boolean { const pawnRow = r + (by === 'w' ? 1 : -1); for (const dc of [-1, 1]) if (this.inside(pawnRow, c + dc) && board[pawnRow][c + dc] === (by === 'w' ? 'P' : 'p')) return true; for (const [dr, dc] of [[-2,-1],[-2,1],[-1,-2],[-1,2],[1,-2],[1,2],[2,-1],[2,1]]) if (this.inside(r + dr, c + dc) && board[r + dr][c + dc] === (by === 'w' ? 'N' : 'n')) return true; const lines = [[1,0],[-1,0],[0,1],[0,-1]]; for (const [dr, dc] of lines) { let nr = r + dr; let nc = c + dc; while (this.inside(nr, nc)) { const piece = board[nr][nc]; if (piece) { if (piece === (by === 'w' ? 'R' : 'r') || piece === (by === 'w' ? 'Q' : 'q')) return true; break; } nr += dr; nc += dc; } } const diagonals = [[1,1],[1,-1],[-1,1],[-1,-1]]; for (const [dr, dc] of diagonals) { let nr = r + dr; let nc = c + dc; while (this.inside(nr, nc)) { const piece = board[nr][nc]; if (piece) { if (piece === (by === 'w' ? 'B' : 'b') || piece === (by === 'w' ? 'Q' : 'q')) return true; break; } nr += dr; nc += dc; } } for (const [dr, dc] of [...lines, ...diagonals]) if (this.inside(r + dr, c + dc) && board[r + dr][c + dc] === (by === 'w' ? 'K' : 'k')) return true; return false; }
  private inside(r: number, c: number): boolean { return r >= 0 && r < 8 && c >= 0 && c < 8; }
}
