import { Action, asInt, GameEngine, GameId, GameOutcome, GamePlayer, GameState, IllegalMoveError, clone, randomInt, rotateTurn } from '../game.types';

const COLORS = ['red', 'yellow', 'green', 'blue'];
interface OchoCard { color: string; value: string; }
interface OchoState extends GameState { hands: OchoCard[][]; draw: OchoCard[]; discard: OchoCard[]; currentColor: string; direction: 1 | -1; turnIndex: number; turnPlayerId: string; winnerId: string | null; finished: boolean; pendingDraw?: number; }

export class OchoEngine implements GameEngine {
  readonly id: GameId = 'ocho';
  create(players: GamePlayer[]): OchoState { const deck = this.deck(); const hands = players.map(() => deck.splice(0, 7)); const first = deck.pop() as OchoCard; const draw = deck; return { hands, draw, discard: [first], currentColor: first.color === 'wild' ? 'red' : first.color, direction: 1, turnIndex: 0, turnPlayerId: players[0].id, winnerId: null, finished: false }; }
  validate(state: OchoState, actorId: string, action: Action, players: GamePlayer[]): void { if (state.finished) throw new IllegalMoveError('This game has finished.'); if (state.turnPlayerId !== actorId) throw new IllegalMoveError('It is not your turn.'); const side = players.findIndex((p) => p.id === actorId); if (action.type === 'draw') return; if (action.type !== 'play') throw new IllegalMoveError('Use play or draw.'); const index = asInt(action.index, 'index', 0, state.hands[side].length - 1); const card = state.hands[side][index]; const top = state.discard[state.discard.length - 1]; const playable = card.color === 'wild' || card.color === state.currentColor || card.value === top.value; if (!playable) throw new IllegalMoveError('That card cannot be played.'); if (card.color === 'wild' && (typeof action.color !== 'string' || !COLORS.includes(action.color))) throw new IllegalMoveError('Choose a color for a wild card.'); }
  apply(state: OchoState, actorId: string, action: Action, players: GamePlayer[]): OchoState { this.validate(state, actorId, action, players); const next = clone(state) as OchoState; const side = players.findIndex((p) => p.id === actorId); if (action.type === 'draw') { const count = Number(next.pendingDraw ?? 1); for (let i = 0; i < count; i += 1) this.drawOne(next, side); next.pendingDraw = undefined; rotateTurn(next, players, next.direction); return next; } const card = next.hands[side].splice(action.index as number, 1)[0]; next.discard.push(card); if (card.color === 'wild') next.currentColor = action.color as string; else next.currentColor = card.color; if (card.value === 'skip') rotateTurn(next, players, next.direction * 2); else if (card.value === 'reverse') { next.direction = (next.direction * -1) as 1 | -1; rotateTurn(next, players, players.length === 2 ? next.direction * 2 : next.direction); } else if (card.value === 'draw2') { next.pendingDraw = 2; rotateTurn(next, players, next.direction); } else if (card.value === 'wild4') { next.pendingDraw = 4; rotateTurn(next, players, next.direction); } else rotateTurn(next, players, next.direction); if (!next.hands[side].length) { next.finished = true; next.winnerId = actorId; } return next; }
  outcome(state: OchoState, players: GamePlayer[]): GameOutcome { const winner = typeof state.winnerId === 'string' ? state.winnerId : ''; return { finished: Boolean(state.finished), winnerIds: winner ? [winner] : [], loserIds: winner ? players.filter((p) => p.id !== winner).map((p) => p.id) : [], draw: false }; }
  botAction(state: OchoState, botId: string, players: GamePlayer[]): Action { const side = players.findIndex((p) => p.id === botId); const top = state.discard[state.discard.length - 1]; const valid = state.hands[side].map((card, index) => card.color === 'wild' || card.color === state.currentColor || card.value === top.value ? index : -1).filter((index) => index >= 0); if (!valid.length) return { type: 'draw' }; const index = valid[randomInt(valid.length)]; const card = state.hands[side][index]; return { type: 'play', index, ...(card.color === 'wild' ? { color: COLORS[randomInt(COLORS.length)] } : {}) }; }
  private drawOne(state: OchoState, side: number): void { if (!state.draw.length) { const top = state.discard.pop() as OchoCard; state.draw = state.discard.splice(0).sort(() => Math.random() - 0.5); state.discard = [top]; } if (state.draw.length) state.hands[side].push(state.draw.pop() as OchoCard); }
  private deck(): OchoCard[] { const deck: OchoCard[] = []; for (const color of COLORS) { deck.push({ color, value: '0' }); for (let i = 1; i <= 2; i += 1) for (const value of ['1','2','3','4','5','6','7','8','9','skip','reverse','draw2']) deck.push({ color, value }); } for (let i = 0; i < 4; i += 1) { deck.push({ color: 'wild', value: 'wild' }); deck.push({ color: 'wild', value: 'wild4' }); } return deck.sort(() => Math.random() - 0.5); }
}

type Suit = 'C' | 'D' | 'H' | 'S';
interface PlayingCard { suit: Suit; rank: number; }
interface TrickState extends GameState { hands: PlayingCard[][]; trick: Array<{ player: number; card: PlayingCard }>; leadSuit: Suit | null; turnIndex: number; turnPlayerId: string; scores: number[]; round: number; winnerId: string | null; finished: boolean; targetScore: number; }

abstract class TrickTakingEngine implements GameEngine {
  abstract readonly id: GameId;
  protected abstract readonly targetScore: number;
  protected abstract scoreTrick(trick: Array<{ player: number; card: PlayingCard }>): number;
  protected abstract winningPlayer(trick: Array<{ player: number; card: PlayingCard }>, lead: Suit): number;
  create(players: GamePlayer[]): TrickState { const deck = this.deck(); const hands = players.map(() => [] as PlayingCard[]); deck.forEach((card, i) => hands[i % players.length].push(card)); return { hands, trick: [], leadSuit: null, turnIndex: 0, turnPlayerId: players[0].id, scores: players.map(() => 0), round: 1, winnerId: null, finished: false, targetScore: this.targetScore }; }
  validate(state: TrickState, actorId: string, action: Action, players: GamePlayer[]): void { if (state.finished) throw new IllegalMoveError('This game has finished.'); if (state.turnPlayerId !== actorId) throw new IllegalMoveError('It is not your turn.'); if (action.type !== 'play') throw new IllegalMoveError('Use play.'); const side = players.findIndex((p) => p.id === actorId); const index = asInt(action.index, 'index', 0, state.hands[side].length - 1); const card = state.hands[side][index]; if (state.leadSuit && card.suit !== state.leadSuit && state.hands[side].some((candidate) => candidate.suit === state.leadSuit)) throw new IllegalMoveError('You must follow the lead suit.'); }
  apply(state: TrickState, actorId: string, action: Action, players: GamePlayer[]): TrickState { this.validate(state, actorId, action, players); const next = clone(state) as TrickState; const side = players.findIndex((p) => p.id === actorId); const card = next.hands[side].splice(action.index as number, 1)[0]; if (!next.leadSuit) next.leadSuit = card.suit; next.trick.push({ player: side, card }); if (next.trick.length === players.length) { const winner = this.winningPlayer(next.trick, next.leadSuit as Suit); next.scores[winner] += this.scoreTrick(next.trick); next.trick = []; next.leadSuit = null; next.turnIndex = winner; next.turnPlayerId = players[winner].id; if (next.scores.some((score) => score >= next.targetScore) || next.hands.every((hand) => !hand.length)) { next.finished = true; const max = Math.max(...next.scores); const winners = next.scores.map((score, i) => score === max ? players[i].id : null).filter((id): id is string => Boolean(id)); next.winnerId = winners[0] ?? null; next.draw = winners.length > 1; } } else rotateTurn(next, players); return next; }
  outcome(state: TrickState, players: GamePlayer[]): GameOutcome { const winner = typeof state.winnerId === 'string' ? state.winnerId : ''; return { finished: Boolean(state.finished), winnerIds: winner ? [winner] : [], loserIds: winner ? players.filter((p) => p.id !== winner).map((p) => p.id) : [], draw: Boolean(state.draw) }; }
  botAction(state: TrickState, botId: string, players: GamePlayer[]): Action { const side = players.findIndex((p) => p.id === botId); const hand = state.hands[side]; const legal = hand.map((card, index) => (!state.leadSuit || card.suit === state.leadSuit || !hand.some((candidate) => candidate.suit === state.leadSuit)) ? index : -1).filter((index) => index >= 0); return { type: 'play', index: legal[randomInt(legal.length)] ?? 0 }; }
  private deck(): PlayingCard[] { const deck: PlayingCard[] = []; for (const suit of ['C','D','H','S'] as Suit[]) for (let rank = 2; rank <= 14; rank += 1) deck.push({ suit, rank }); return deck.sort(() => Math.random() - 0.5); }
}

export class HeartsEngine extends TrickTakingEngine { readonly id: GameId = 'hearts'; protected readonly targetScore = 100; protected scoreTrick(trick: Array<{ player: number; card: PlayingCard }>): number { return trick.reduce((sum, item) => sum + (item.card.suit === 'H' ? 1 : item.card.suit === 'S' && item.card.rank === 12 ? 13 : 0), 0); } protected winningPlayer(trick: Array<{ player: number; card: PlayingCard }>, lead: Suit): number { return trick.filter((item) => item.card.suit === lead).sort((a, b) => b.card.rank - a.card.rank)[0].player; } }
export class SpadesEngine extends TrickTakingEngine { readonly id: GameId = 'spades'; protected readonly targetScore = 500; protected scoreTrick(trick: Array<{ player: number; card: PlayingCard }>): number { return 1; } protected winningPlayer(trick: Array<{ player: number; card: PlayingCard }>, lead: Suit): number { const spades = trick.filter((item) => item.card.suit === 'S'); const pool = spades.length ? spades : trick.filter((item) => item.card.suit === lead); return pool.sort((a, b) => b.card.rank - a.card.rank)[0].player; } }
