import { Action, asInt, asString, GameEngine, GameId, GameOutcome, GamePlayer, GameState, IllegalMoveError, clone, randomInt, rotateTurn } from '../game.types';

const checkTurn = (state: GameState, actorId: string) => { if (state.finished) throw new IllegalMoveError('This game has finished.'); if (state.turnPlayerId !== actorId) throw new IllegalMoveError('It is not your turn.'); };

export class DicePartyEngine implements GameEngine {
  readonly id: GameId = 'dice_party';
  create(players: GamePlayer[]): GameState { return { round: 1, maxRounds: 5, scores: players.map(() => 0), rolls: players.map(() => null), turnIndex: 0, turnPlayerId: players[0].id, finished: false, winnerId: null }; }
  validate(state: GameState, actorId: string, action: Action, players: GamePlayer[]): void { checkTurn(state, actorId); if (action.type !== 'roll') throw new IllegalMoveError('Use roll.'); if ((state.rolls as unknown[])[players.findIndex((p) => p.id === actorId)] !== null) throw new IllegalMoveError('You already rolled this round.'); }
  apply(state: GameState, actorId: string, action: Action, players: GamePlayer[]): GameState { this.validate(state, actorId, action, players); const next = clone(state); const side = players.findIndex((p) => p.id === actorId); const value = randomInt(6) + 1; (next.rolls as (number | null)[])[side] = value; (next.scores as number[])[side] += value; const allRolled = (next.rolls as unknown[]).every((roll) => roll !== null); if (allRolled) { if (Number(next.round) >= Number(next.maxRounds)) { next.finished = true; const max = Math.max(...(next.scores as number[])); next.winnerId = players[(next.scores as number[]).indexOf(max)].id; next.draw = (next.scores as number[]).filter((score) => score === max).length > 1; } else { next.round = Number(next.round) + 1; next.rolls = players.map(() => null); next.turnIndex = 0; next.turnPlayerId = players[0].id; } } else rotateTurn(next, players); return next; }
  outcome(state: GameState, players: GamePlayer[]): GameOutcome { const winner = typeof state.winnerId === 'string' ? state.winnerId : ''; return { finished: Boolean(state.finished), winnerIds: winner ? [winner] : [], loserIds: winner ? players.filter((p) => p.id !== winner).map((p) => p.id) : [], draw: Boolean(state.draw) }; }
  botAction(): Action { return { type: 'roll' }; }
}

export class BingoEngine implements GameEngine {
  readonly id: GameId = 'bingo';
  create(players: GamePlayer[]): GameState { const cards = players.map(() => { const values = Array.from({ length: 25 }, (_, i) => i + 1).sort(() => Math.random() - 0.5); return { values, marked: Array(25).fill(false) as boolean[] }; }); return { cards, called: [], bag: Array.from({ length: 75 }, (_, i) => i + 1).sort(() => Math.random() - 0.5), turnIndex: 0, turnPlayerId: players[0].id, finished: false, winnerId: null }; }
  validate(state: GameState, actorId: string, action: Action, players: GamePlayer[]): void { checkTurn(state, actorId); if (action.type !== 'call') throw new IllegalMoveError('Use call.'); const number = asInt(action.number, 'number', 1, 75); if (!(state.bag as number[]).includes(number)) throw new IllegalMoveError('That number has already been called.'); }
  apply(state: GameState, actorId: string, action: Action, players: GamePlayer[]): GameState { this.validate(state, actorId, action, players); const next = clone(state); const number = action.number as number; next.bag = (next.bag as number[]).filter((value) => value !== number); (next.called as number[]).push(number); for (const card of next.cards as Array<{ values: number[]; marked: boolean[] }>) { const position = card.values.indexOf(number); if (position >= 0) card.marked[position] = true; } const winnerIndex = (next.cards as Array<{ values: number[]; marked: boolean[] }>).findIndex((card) => this.hasBingo(card.marked)); if (winnerIndex >= 0) { next.finished = true; next.winnerId = players[winnerIndex].id; } else if (!(next.bag as number[]).length) { next.finished = true; next.draw = true; } else rotateTurn(next, players); return next; }
  outcome(state: GameState, players: GamePlayer[]): GameOutcome { const winner = typeof state.winnerId === 'string' ? state.winnerId : ''; return { finished: Boolean(state.finished), winnerIds: winner ? [winner] : [], loserIds: winner ? players.filter((p) => p.id !== winner).map((p) => p.id) : [], draw: Boolean(state.draw) }; }
  botAction(state: GameState, botId: string, players: GamePlayer[]): Action { const bag = state.bag as number[]; return { type: 'call', number: bag[randomInt(bag.length)] ?? 1 }; }
  private hasBingo(marked: boolean[]): boolean { return [0,1,2,3,4].some((r) => [0,1,2,3,4].every((c) => marked[r * 5 + c])) || [0,1,2,3,4].some((c) => [0,1,2,3,4].every((r) => marked[r * 5 + c])) || [0,1,2,3,4].every((i) => marked[i * 5 + i]) || [0,1,2,3,4].every((i) => marked[i * 5 + (4 - i)]); }
}

interface WerewolfState extends GameState { roles: string[]; alive: boolean[]; phase: 'night' | 'day'; nightTarget: number | null; votes: Array<number | null>; turnIndex: number; turnPlayerId: string; finished: boolean; winnerIds: string[]; }
export class WerewolfEngine implements GameEngine {
  readonly id: GameId = 'werewolf';
  create(players: GamePlayer[]): WerewolfState { const roles = players.map((_, i) => i < Math.max(1, Math.floor(players.length / 4)) ? 'werewolf' : i === players.length - 1 ? 'seer' : 'villager').sort(() => Math.random() - 0.5); return { roles, alive: players.map(() => true), phase: 'night', nightTarget: null, votes: players.map(() => null), turnIndex: 0, turnPlayerId: players[0].id, finished: false, winnerIds: [] }; }
  validate(state: WerewolfState, actorId: string, action: Action, players: GamePlayer[]): void { if (state.finished) throw new IllegalMoveError('This game has finished.'); const side = players.findIndex((p) => p.id === actorId); if (side < 0 || !state.alive[side]) throw new IllegalMoveError('You are out of the game.'); if (state.phase === 'night' && action.type !== 'night') throw new IllegalMoveError('Night actions are required.'); if (state.phase === 'day' && action.type !== 'vote') throw new IllegalMoveError('Vote during the day.'); const target = asInt(action.target, 'target', 0, players.length - 1); if (!state.alive[target] || target === side && action.type === 'night') throw new IllegalMoveError('Choose a living target.'); }
  apply(state: WerewolfState, actorId: string, action: Action, players: GamePlayer[]): WerewolfState { this.validate(state, actorId, action, players); const next = clone(state) as WerewolfState; const side = players.findIndex((p) => p.id === actorId); const target = action.target as number; if (next.phase === 'night') { if (next.roles[side] === 'werewolf') next.nightTarget = target; const acted = players.every((_, i) => !next.alive[i] || next.roles[i] !== 'werewolf' || next.nightTarget !== null); if (acted) { if (next.nightTarget !== null) next.alive[next.nightTarget] = false; next.nightTarget = null; next.phase = 'day'; next.votes = players.map(() => null); next.turnIndex = players.findIndex((_, i) => next.alive[i]); next.turnPlayerId = players[next.turnIndex].id; } } else { next.votes[side] = target; const voted = players.every((_, i) => !next.alive[i] || next.votes[i] !== null); if (voted) { const counts = players.map((_, i) => next.votes.filter((vote) => vote === i).length); const max = Math.max(...counts); const eliminated = counts.indexOf(max); if (max > 0) next.alive[eliminated] = false; const wolves = next.roles.filter((role, i) => role === 'werewolf' && next.alive[i]).length; const villagers = next.alive.filter((alive, i) => alive && next.roles[i] !== 'werewolf').length; if (!wolves || wolves >= villagers) { next.finished = true; next.winnerIds = wolves ? players.filter((_, i) => next.roles[i] === 'werewolf').map((p) => p.id) : players.filter((_, i) => next.roles[i] !== 'werewolf').map((p) => p.id); } else { next.phase = 'night'; next.votes = players.map(() => null); next.turnIndex = next.alive.findIndex(Boolean); next.turnPlayerId = players[next.turnIndex].id; } } } return next; }
  outcome(state: WerewolfState): GameOutcome { return { finished: Boolean(state.finished), winnerIds: state.winnerIds, loserIds: [], draw: false }; }
  botAction(state: WerewolfState, botId: string, players: GamePlayer[]): Action { const side = players.findIndex((p) => p.id === botId); const candidates = players.map((_, i) => i).filter((i) => state.alive[i] && i !== side); return { type: state.phase === 'night' ? 'night' : 'vote', target: candidates[randomInt(candidates.length)] ?? 0 }; }
}

export class WordChainEngine implements GameEngine {
  readonly id: GameId = 'word_chain';
  create(players: GamePlayer[]): GameState { return { words: [], used: [], requiredLetter: null, scores: players.map(() => 0), turnIndex: 0, turnPlayerId: players[0].id, finished: false, winnerId: null, passCount: 0 }; }
  validate(state: GameState, actorId: string, action: Action, players: GamePlayer[]): void { checkTurn(state, actorId); if (action.type !== 'word') throw new IllegalMoveError('Submit a word.'); const word = asString(action.word, 'word').toLowerCase(); if (!/^[a-zA-Z\u0600-\u06ff]{2,24}$/.test(word)) throw new IllegalMoveError('Use a word with two to twenty-four letters.'); if ((state.used as string[]).includes(word)) throw new IllegalMoveError('That word has already been used.'); if (state.requiredLetter && !word.startsWith(state.requiredLetter as string)) throw new IllegalMoveError(`Your word must start with ${state.requiredLetter}.`); }
  apply(state: GameState, actorId: string, action: Action, players: GamePlayer[]): GameState { this.validate(state, actorId, action, players); const next = clone(state); const word = (action.word as string).toLowerCase(); (next.words as string[]).push(word); (next.used as string[]).push(word); (next.scores as number[])[players.findIndex((p) => p.id === actorId)] += word.length; next.requiredLetter = word[word.length - 1]; next.passCount = 0; rotateTurn(next, players); return next; }
  outcome(state: GameState, players: GamePlayer[]): GameOutcome { const winner = typeof state.winnerId === 'string' ? state.winnerId : ''; return { finished: Boolean(state.finished), winnerIds: winner ? [winner] : [], loserIds: winner ? players.filter((p) => p.id !== winner).map((p) => p.id) : [], draw: false }; }
  botAction(state: GameState): Action { const letter = (state.requiredLetter as string | null) ?? 'v'; return { type: 'word', word: `${letter}ibe` }; }
}

export class MemoryRaceEngine implements GameEngine {
  readonly id: GameId = 'memory_race';
  create(players: GamePlayer[]): GameState { const values = Array.from({ length: 12 }, (_, i) => i).flatMap((i) => [i, i]).sort(() => Math.random() - 0.5); return { values, revealed: Array(24).fill(false), matched: Array(24).fill(false), selections: [], scores: players.map(() => 0), turnIndex: 0, turnPlayerId: players[0].id, finished: false, winnerId: null }; }
  validate(state: GameState, actorId: string, action: Action, players: GamePlayer[]): void { checkTurn(state, actorId); if (action.type !== 'flip') throw new IllegalMoveError('Flip a card.'); const index = asInt(action.index, 'index', 0, 23); if ((state.revealed as boolean[])[index] || (state.matched as boolean[])[index]) throw new IllegalMoveError('That card is not available.'); }
  apply(state: GameState, actorId: string, action: Action, players: GamePlayer[]): GameState { this.validate(state, actorId, action, players); const next = clone(state); const index = action.index as number; (next.revealed as boolean[])[index] = true; (next.selections as number[]).push(index); if ((next.selections as number[]).length === 2) { const selections = next.selections as number[]; if ((next.values as number[])[selections[0]] === (next.values as number[])[selections[1]]) { (next.matched as boolean[])[selections[0]] = true; (next.matched as boolean[])[selections[1]] = true; (next.scores as number[])[players.findIndex((p) => p.id === actorId)] += 1; } else { (next.revealed as boolean[])[selections[0]] = false; (next.revealed as boolean[])[selections[1]] = false; rotateTurn(next, players); } next.selections = []; if ((next.matched as boolean[]).every(Boolean)) { next.finished = true; const max = Math.max(...(next.scores as number[])); next.winnerId = players[(next.scores as number[]).indexOf(max)].id; } } return next; }
  outcome(state: GameState, players: GamePlayer[]): GameOutcome { const winner = typeof state.winnerId === 'string' ? state.winnerId : ''; return { finished: Boolean(state.finished), winnerIds: winner ? [winner] : [], loserIds: winner ? players.filter((p) => p.id !== winner).map((p) => p.id) : [], draw: false }; }
  botAction(state: GameState): Action { const available = (state.matched as boolean[]).map((matched, i) => !matched && !(state.revealed as boolean[])[i] ? i : -1).filter((i) => i >= 0); return { type: 'flip', index: available[randomInt(available.length)] ?? 0 }; }
}

export class KnowledgeEngine implements GameEngine {
  readonly id: GameId;
  private readonly questionCount: number;
  constructor(id: GameId, questionCount = 10) { this.id = id; this.questionCount = questionCount; }
  create(players: GamePlayer[]): GameState { return { question: 1, questionCount: this.questionCount, answered: players.map(() => false), scores: players.map(() => 0), turnIndex: 0, turnPlayerId: players[0].id, finished: false, winnerId: null }; }
  validate(state: GameState, actorId: string, action: Action, players: GamePlayer[]): void { checkTurn(state, actorId); if (action.type !== 'answer') throw new IllegalMoveError('Answer the current challenge.'); asInt(action.answer, 'answer', 0, 3); const side = players.findIndex((p) => p.id === actorId); if ((state.answered as boolean[])[side]) throw new IllegalMoveError('You already answered this question.'); }
  apply(state: GameState, actorId: string, action: Action, players: GamePlayer[]): GameState { this.validate(state, actorId, action, players); const next = clone(state); const side = players.findIndex((p) => p.id === actorId); (next.answered as boolean[])[side] = true; if ((action.answer as number) === Number(next.question) % 4) (next.scores as number[])[side] += 100 + randomInt(50); if ((next.answered as boolean[]).every(Boolean)) { if (Number(next.question) >= Number(next.questionCount)) { next.finished = true; const max = Math.max(...(next.scores as number[])); next.winnerId = players[(next.scores as number[]).indexOf(max)].id; next.draw = (next.scores as number[]).filter((score) => score === max).length > 1; } else { next.question = Number(next.question) + 1; next.answered = players.map(() => false); next.turnIndex = 0; next.turnPlayerId = players[0].id; } } else rotateTurn(next, players); return next; }
  outcome(state: GameState, players: GamePlayer[]): GameOutcome { const winner = typeof state.winnerId === 'string' ? state.winnerId : ''; return { finished: Boolean(state.finished), winnerIds: winner ? [winner] : [], loserIds: winner ? players.filter((p) => p.id !== winner).map((p) => p.id) : [], draw: Boolean(state.draw) }; }
  botAction(state: GameState): Action { return { type: 'answer', answer: randomInt(4) }; }
}

export class ImpostorLightEngine implements GameEngine {
  readonly id: GameId = 'impostor_light';
  create(players: GamePlayer[]): GameState { const impostor = randomInt(players.length); return { impostor, clues: players.map(() => null), votes: players.map(() => null), phase: 'clues', turnIndex: 0, turnPlayerId: players[0].id, finished: false, winnerId: null }; }
  validate(state: GameState, actorId: string, action: Action, players: GamePlayer[]): void { checkTurn(state, actorId); const side = players.findIndex((p) => p.id === actorId); if (state.phase === 'clues' && action.type !== 'clue') throw new IllegalMoveError('Give a clue.'); if (state.phase === 'vote' && action.type !== 'vote') throw new IllegalMoveError('Vote for the impostor.'); if (state.phase === 'clues') asString(action.clue, 'clue'); else { const target = asInt(action.target, 'target', 0, players.length - 1); if (target === side) throw new IllegalMoveError('You cannot vote for yourself.'); } }
  apply(state: GameState, actorId: string, action: Action, players: GamePlayer[]): GameState { this.validate(state, actorId, action, players); const next = clone(state); const side = players.findIndex((p) => p.id === actorId); if (next.phase === 'clues') { (next.clues as (string | null)[])[side] = (action.clue as string).slice(0, 100); if ((next.clues as unknown[]).every(Boolean)) { next.phase = 'vote'; next.votes = players.map(() => null); next.turnIndex = 0; next.turnPlayerId = players[0].id; } else rotateTurn(next, players); } else { (next.votes as (number | null)[])[side] = action.target as number; if ((next.votes as unknown[]).every((vote) => vote !== null)) { const target = (next.votes as number[]).sort((a, b) => (next.votes as number[]).filter((v) => v === b).length - (next.votes as number[]).filter((v) => v === a).length)[0]; next.finished = true; next.winnerId = target === Number(next.impostor) ? players.find((p) => p.id !== players[Number(next.impostor)].id)?.id ?? null : players[Number(next.impostor)].id; next.impostorCaught = target === Number(next.impostor); } else rotateTurn(next, players); } return next; }
  outcome(state: GameState, players: GamePlayer[]): GameOutcome { const winner = typeof state.winnerId === 'string' ? state.winnerId : ''; return { finished: Boolean(state.finished), winnerIds: winner ? [winner] : [], loserIds: winner ? players.filter((p) => p.id !== winner).map((p) => p.id) : [], draw: false }; }
  botAction(state: GameState, botId: string, players: GamePlayer[]): Action { const side = players.findIndex((p) => p.id === botId); return state.phase === 'clues' ? { type: 'clue', clue: 'bright' } : { type: 'vote', target: players.findIndex((_, i) => i !== side) }; }
}

export class EmojiCharadesEngine extends KnowledgeEngine { readonly id: GameId = 'emoji_charades'; constructor() { super('emoji_charades', 7); } }
export class SketchGuessEngine extends KnowledgeEngine { readonly id: GameId = 'sketch_guess'; constructor() { super('sketch_guess', 7); } }
export class TriviaBattleEngine extends KnowledgeEngine { readonly id: GameId = 'trivia_battle'; constructor() { super('trivia_battle', 10); } }
export class QuickChallengesEngine extends KnowledgeEngine { readonly id: GameId = 'quick_challenges'; constructor() { super('quick_challenges', 7); } }
