import { Action, asInt, GameEngine, GameId, GameOutcome, GamePlayer, GameState, IllegalMoveError, clone, nextTurn, randomInt, rotateTurn } from '../game.types';

const ensureTurn = (state: GameState, actorId: string) => { if (state.turnPlayerId !== actorId) throw new IllegalMoveError('It is not your turn.'); if (state.finished) throw new IllegalMoveError('This game has finished.'); };

export class LudoEngine implements GameEngine {
  readonly id: GameId = 'ludo';
  create(players: GamePlayer[]): GameState { return { positions: players.map(() => [-1, -1, -1, -1]), rolls: players.map(() => 0), pendingRoll: null, turnIndex: 0, turnPlayerId: players[0].id, finished: false, winnerId: null }; }
  validate(state: GameState, actorId: string, action: Action, players: GamePlayer[]): void { ensureTurn(state, actorId); const side = players.findIndex((p) => p.id === actorId); if (action.type === 'roll') { if (state.pendingRoll) throw new IllegalMoveError('Move a token before rolling again.'); return; } if (action.type !== 'move' || !state.pendingRoll) throw new IllegalMoveError('Roll the dice first.'); const token = asInt(action.token, 'token', 0, 3); const position = (state.positions as number[][])[side][token]; const die = Number(state.pendingRoll); if (position === 99 || (position === -1 && die !== 6) || (position >= 0 && position + die > 56)) throw new IllegalMoveError('That token cannot move with this roll.'); }
  apply(state: GameState, actorId: string, action: Action, players: GamePlayer[]): GameState { this.validate(state, actorId, action, players); const next = clone(state); const side = players.findIndex((p) => p.id === actorId); if (action.type === 'roll') { next.pendingRoll = randomInt(6) + 1; return next; } const die = Number(next.pendingRoll); const tokens = next.positions as number[][]; const token = action.token as number; tokens[side][token] = tokens[side][token] === -1 ? 0 : tokens[side][token] + die; if (tokens[side][token] >= 56) tokens[side][token] = 99; const absolute = tokens[side][token] >= 0 && tokens[side][token] < 52 ? (side * 13 + tokens[side][token]) % 52 : -1; for (let other = 0; other < tokens.length; other += 1) if (other !== side) for (let t = 0; t < 4; t += 1) { const otherPos = tokens[other][t]; if (absolute >= 0 && otherPos >= 0 && otherPos < 52 && (other * 13 + otherPos) % 52 === absolute) tokens[other][t] = -1; } const won = tokens[side].every((value) => value === 99); next.pendingRoll = null; if (won) { next.finished = true; next.winnerId = actorId; } else if (die !== 6) rotateTurn(next, players); return next; }
  outcome(state: GameState, players: GamePlayer[]): GameOutcome { const winner = typeof state.winnerId === 'string' ? state.winnerId : ''; return { finished: Boolean(state.finished), winnerIds: winner ? [winner] : [], loserIds: winner ? players.filter((p) => p.id !== winner).map((p) => p.id) : [], draw: false }; }
  botAction(state: GameState, botId: string, players: GamePlayer[]): Action { const side = players.findIndex((p) => p.id === botId); if (!state.pendingRoll) return { type: 'roll' }; const die = Number(state.pendingRoll); const tokens = (state.positions as number[][])[side]; const valid = tokens.map((position, token) => position !== 99 && (position === -1 ? die === 6 : position + die <= 56) ? token : -1).filter((token) => token >= 0); return { type: 'move', token: valid[randomInt(valid.length)] ?? 0 }; }
}

interface DominoState extends GameState { hands: number[][][]; chain: number[]; boneyard: number[][]; turnIndex: number; turnPlayerId: string; finished: boolean; winnerId: string | null; draw?: boolean; }
export class DominoesEngine implements GameEngine {
  readonly id: GameId = 'dominoes';
  create(players: GamePlayer[]): DominoState { const deck: number[][] = []; for (let a = 0; a <= 6; a += 1) for (let b = a; b <= 6; b += 1) deck.push([a, b]); for (let i = deck.length - 1; i > 0; i -= 1) { const j = randomInt(i + 1); [deck[i], deck[j]] = [deck[j], deck[i]]; } const hands = players.map(() => deck.splice(0, 7)); return { hands, chain: [], boneyard: deck, turnIndex: 0, turnPlayerId: players[0].id, finished: false, winnerId: null }; }
  validate(state: DominoState, actorId: string, action: Action, players: GamePlayer[]): void { ensureTurn(state, actorId); const side = players.findIndex((p) => p.id === actorId); if (action.type === 'draw') { if (!state.boneyard.length) throw new IllegalMoveError('The boneyard is empty.'); return; } if (action.type !== 'play') throw new IllegalMoveError('Use play or draw.'); const index = asInt(action.index, 'index', 0, state.hands[side].length - 1); const tile = state.hands[side][index]; const left = state.chain[0]; const right = state.chain[state.chain.length - 1]; if (state.chain.length && tile[0] !== left && tile[1] !== left && tile[0] !== right && tile[1] !== right) throw new IllegalMoveError('That tile does not match either end.'); if (action.side !== undefined && action.side !== 'left' && action.side !== 'right') throw new IllegalMoveError('side must be left or right.'); }
  apply(state: DominoState, actorId: string, action: Action, players: GamePlayer[]): DominoState { this.validate(state, actorId, action, players); const next = clone(state) as DominoState; const side = players.findIndex((p) => p.id === actorId); if (action.type === 'draw') { next.hands[side].push(next.boneyard.pop() as number[]); return next; } const tile = next.hands[side].splice(action.index as number, 1)[0]; if (!next.chain.length) next.chain.push(...tile); else { const place = action.side === 'left' ? 'left' : action.side === 'right' ? 'right' : tile.includes(next.chain[0]) ? 'left' : 'right'; if (place === 'left') { const value = next.chain[0]; const oriented = tile[0] === value ? [tile[1], tile[0]] : [tile[0], tile[1]]; next.chain.unshift(...oriented); } else { const value = next.chain[next.chain.length - 1]; const oriented = tile[0] === value ? tile : [tile[1], tile[0]]; next.chain.push(...oriented); } } if (!next.hands[side].length) { next.finished = true; next.winnerId = actorId; } else if (!this.hasAnyMove(next.hands, next.chain) && !next.boneyard.length) { next.finished = true; const scores = next.hands.map((hand) => hand.reduce((sum, tile) => sum + tile[0] + tile[1], 0)); const min = Math.min(...scores); const winner = scores.indexOf(min); next.winnerId = players[winner].id; next.draw = scores.filter((score) => score === min).length > 1; } else rotateTurn(next, players); return next; }
  outcome(state: DominoState, players: GamePlayer[]): GameOutcome { const winner = typeof state.winnerId === 'string' ? state.winnerId : ''; return { finished: Boolean(state.finished), winnerIds: winner ? [winner] : [], loserIds: winner ? players.filter((p) => p.id !== winner).map((p) => p.id) : [], draw: Boolean(state.draw) }; }
  botAction(state: DominoState, botId: string, players: GamePlayer[]): Action { const side = players.findIndex((p) => p.id === botId); const legal = state.hands[side].map((tile, index) => ({ tile, index })).filter(({ tile }) => !state.chain.length || tile.some((v) => v === state.chain[0] || v === state.chain[state.chain.length - 1])); return legal.length ? { type: 'play', index: legal[0].index, side: 'right' } : { type: 'draw' }; }
  private hasAnyMove(hands: number[][][], chain: number[]): boolean { return hands.some((hand) => hand.some((tile) => !chain.length || tile.some((v) => v === chain[0] || v === chain[chain.length - 1]))); }
}

interface BackgammonState extends GameState { points: number[]; bar: number[]; borneOff: number[]; dice: number[]; turnIndex: number; turnPlayerId: string; finished: boolean; winnerId: string | null; }
export class BackgammonEngine implements GameEngine {
  readonly id: GameId = 'backgammon';
  create(players: GamePlayer[]): BackgammonState { const points = Array(24).fill(0); points[0] = 2; points[11] = 5; points[16] = 3; points[18] = 5; points[23] = -2; points[12] = -5; points[7] = -3; points[5] = -5; return { points, bar: [0, 0], borneOff: [0, 0], dice: [], turnIndex: 0, turnPlayerId: players[0].id, finished: false, winnerId: null }; }
  validate(state: BackgammonState, actorId: string, action: Action, players: GamePlayer[]): void { ensureTurn(state, actorId); const side = players.findIndex((p) => p.id === actorId); if (action.type === 'roll') { if (state.dice.length) throw new IllegalMoveError('Use all dice before rolling.'); return; } if (action.type !== 'move' || !state.dice.length) throw new IllegalMoveError('Roll before moving.'); const from = asInt(action.from, 'from', -1, 23); const to = asInt(action.to, 'to', -1, 24); const points = state.points; const own = side === 0 ? 1 : -1; if (state.bar[side] > 0 && from !== -1) throw new IllegalMoveError('Move a checker from the bar first.'); if (from !== -1 && Math.sign(points[from]) !== own) throw new IllegalMoveError('That point does not contain your checker.'); const distance = side === 0 ? to - from : from - to; if (!state.dice.includes(distance)) throw new IllegalMoveError('That die is not available.'); if (to >= 0 && to < 24 && points[to] * own < -1) throw new IllegalMoveError('That point is blocked.'); }
  apply(state: BackgammonState, actorId: string, action: Action, players: GamePlayer[]): BackgammonState { this.validate(state, actorId, action, players); const next = clone(state) as BackgammonState; const side = players.findIndex((p) => p.id === actorId); if (action.type === 'roll') { const a = randomInt(6) + 1; const b = randomInt(6) + 1; next.dice = a === b ? [a, a, a, a] : [a, b]; return next; } const from = action.from as number; const to = action.to as number; const own = side === 0 ? 1 : -1; const die = side === 0 ? to - from : from - to; const dieIndex = next.dice.indexOf(die); next.dice.splice(dieIndex, 1); if (from === -1) next.bar[side] -= 1; else next.points[from] -= own; if (to < 0 || to > 23) next.borneOff[side] += 1; else { if (next.points[to] * own === -1) { next.points[to] = 0; next.bar[1 - side] += 1; } next.points[to] += own; } if (next.borneOff[side] === 15) { next.finished = true; next.winnerId = actorId; } else if (!next.dice.length) rotateTurn(next, players); return next; }
  outcome(state: BackgammonState, players: GamePlayer[]): GameOutcome { const winner = typeof state.winnerId === 'string' ? state.winnerId : ''; return { finished: Boolean(state.finished), winnerIds: winner ? [winner] : [], loserIds: winner ? players.filter((p) => p.id !== winner).map((p) => p.id) : [], draw: false }; }
  botAction(state: BackgammonState, botId: string, players: GamePlayer[]): Action { if (!state.dice.length) return { type: 'roll' }; const side = players.findIndex((p) => p.id === botId); const own = side === 0 ? 1 : -1; for (let from = 0; from < 24; from += 1) if (state.points[from] * own > 0) for (const die of state.dice) { const to = side === 0 ? from + die : from - die; if ((to < 0 || to > 23 || state.points[to] * own >= -1) && (to < 0 || to > 23 || Math.sign(state.points[to]) === own || state.points[to] === 0 || state.points[to] * own === -1)) return { type: 'move', from, to }; } return { type: 'move', from: -1, to: side === 0 ? state.dice[0] - 1 : 24 - state.dice[0] }; }
}

export class SeaBattleEngine implements GameEngine {
  readonly id: GameId = 'sea_battle';
  create(players: GamePlayer[]): GameState { return { boards: players.map(() => Array.from({ length: 10 }, () => Array(10).fill(0))), shots: players.map(() => Array.from({ length: 10 }, () => Array(10).fill(-1))), fleets: players.map(() => []), phase: 'placing', turnIndex: 0, turnPlayerId: null, finished: false, winnerId: null }; }
  validate(state: GameState, actorId: string, action: Action, players: GamePlayer[]): void { const side = players.findIndex((p) => p.id === actorId); if (side < 0) throw new IllegalMoveError('You are not in this game.'); if (state.phase === 'placing') { if (action.type !== 'place') throw new IllegalMoveError('Place your fleet first.'); const cells = action.cells; if (!Array.isArray(cells) || !cells.length) throw new IllegalMoveError('A ship needs cells.'); const sizes = [5, 4, 3, 3, 2]; const fleets = state.fleets as unknown[][][]; if (fleets[side].length >= sizes.length) throw new IllegalMoveError('Your fleet is already placed.'); const expected = sizes[fleets[side].length]; if (cells.length !== expected) throw new IllegalMoveError('Incorrect ship size.'); const board = (state.boards as number[][][])[side]; for (const raw of cells) { if (!Array.isArray(raw) || raw.length !== 2) throw new IllegalMoveError('Invalid ship coordinate.'); const r = asInt(raw[0], 'row', 0, 9); const c = asInt(raw[1], 'column', 0, 9); if (board[r][c]) throw new IllegalMoveError('Ships may not overlap.'); } return; } if (action.type !== 'fire') throw new IllegalMoveError('Use fire to attack.'); ensureTurn(state, actorId); asInt(action.row, 'row', 0, 9); asInt(action.column, 'column', 0, 9); const shots = (state.shots as number[][][])[side]; if (shots[action.row as number][action.column as number] !== -1) throw new IllegalMoveError('You already fired there.'); }
  apply(state: GameState, actorId: string, action: Action, players: GamePlayer[]): GameState { this.validate(state, actorId, action, players); const next = clone(state); const side = players.findIndex((p) => p.id === actorId); if (next.phase === 'placing') { const cells = action.cells as number[][]; const board = (next.boards as number[][][])[side]; const fleet = (next.fleets as number[][][][])[side]; const id = fleet.length + 1; for (const [r, c] of cells) board[r][c] = id; fleet.push(cells); if ((next.fleets as unknown[][][]).every((ships) => ships.length === 5)) { next.phase = 'battle'; next.turnPlayerId = players[0].id; } return next; } const opponent = 1 - side; const row = action.row as number; const column = action.column as number; const shots = (next.shots as number[][][])[side]; const target = (next.boards as number[][][])[opponent][row][column]; shots[row][column] = target ? 1 : 0; if (target) (next.boards as number[][][])[opponent][row][column] = -target; const remaining = (next.boards as number[][][])[opponent].flat().some((cell) => cell > 0); if (!remaining) { next.finished = true; next.winnerId = actorId; } else rotateTurn(next, players); return next; }
  outcome(state: GameState, players: GamePlayer[]): GameOutcome { const winner = typeof state.winnerId === 'string' ? state.winnerId : ''; return { finished: Boolean(state.finished), winnerIds: winner ? [winner] : [], loserIds: winner ? players.filter((p) => p.id !== winner).map((p) => p.id) : [], draw: false }; }
  botAction(state: GameState, botId: string, players: GamePlayer[]): Action { const side = players.findIndex((p) => p.id === botId); if (state.phase === 'placing') { const sizes = [5,4,3,3,2]; const size = sizes[(state.fleets as unknown[][][])[side].length]; const row = (state.fleets as unknown[][][])[side].length; return { type: 'place', cells: Array.from({ length: size }, (_, i) => [row, i]) }; } const shots = (state.shots as number[][][])[side]; const open: Array<[number, number]> = []; for (let r = 0; r < 10; r += 1) for (let c = 0; c < 10; c += 1) if (shots[r][c] === -1) open.push([r, c]); const [row, column] = open[randomInt(open.length)] ?? [0, 0]; return { type: 'fire', row, column }; }
}

export class PoolEngine implements GameEngine {
  readonly id: GameId = 'pool_8_ball';
  create(players: GamePlayer[]): GameState { return { balls: { solids: 7, stripes: 7, eight: true }, scores: players.map(() => 0), turnIndex: 0, turnPlayerId: players[0].id, shots: 0, finished: false, winnerId: null }; }
  validate(state: GameState, actorId: string, action: Action, players: GamePlayer[]): void { ensureTurn(state, actorId); if (action.type !== 'shot') throw new IllegalMoveError('Use the shot action.'); asInt(action.power, 'power', 1, 100); asInt(action.pocket, 'pocket', 0, 5); if (!players.some((p) => p.id === actorId)) throw new IllegalMoveError('You are not in this game.'); }
  apply(state: GameState, actorId: string, action: Action, players: GamePlayer[]): GameState { this.validate(state, actorId, action, players); const next = clone(state); const side = players.findIndex((p) => p.id === actorId); const chance = (action.power as number) / 100; const scored = Math.random() < chance; next.shots = Number(next.shots) + 1; if (scored) { (next.scores as number[])[side] += 1; if ((next.scores as number[])[side] >= 8) { next.finished = true; next.winnerId = actorId; } } if (!next.finished && !scored) rotateTurn(next, players); return next; }
  outcome(state: GameState, players: GamePlayer[]): GameOutcome { const winner = typeof state.winnerId === 'string' ? state.winnerId : ''; return { finished: Boolean(state.finished), winnerIds: winner ? [winner] : [], loserIds: winner ? players.filter((p) => p.id !== winner).map((p) => p.id) : [], draw: false }; }
  botAction(): Action { return { type: 'shot', power: 65, pocket: randomInt(6) }; }
}

export class CarromEngine implements GameEngine {
  readonly id: GameId = 'carrom';
  create(players: GamePlayer[]): GameState { return { coinsRemaining: 19, queenRemaining: true, scores: players.map(() => 0), turnIndex: 0, turnPlayerId: players[0].id, finished: false, winnerId: null }; }
  validate(state: GameState, actorId: string, action: Action, players: GamePlayer[]): void { ensureTurn(state, actorId); if (action.type !== 'strike') throw new IllegalMoveError('Use strike.'); asInt(action.power, 'power', 1, 100); asInt(action.pocketed, 'pocketed', 0, 3); if (Number(state.coinsRemaining) <= 0) throw new IllegalMoveError('The board has no coins left.'); if (!players.some((p) => p.id === actorId)) throw new IllegalMoveError('You are not in this game.'); }
  apply(state: GameState, actorId: string, action: Action, players: GamePlayer[]): GameState { this.validate(state, actorId, action, players); const next = clone(state); const side = players.findIndex((p) => p.id === actorId); const pocketed = Math.min(Number(action.pocketed), Number(next.coinsRemaining)); next.coinsRemaining = Number(next.coinsRemaining) - pocketed; (next.scores as number[])[side] += pocketed; if (action.queen === true && next.queenRemaining && pocketed > 0) { next.queenRemaining = false; (next.scores as number[])[side] += 3; } if ((next.scores as number[])[side] >= 9 || (Number(next.coinsRemaining) === 0 && !next.queenRemaining)) { next.finished = true; next.winnerId = actorId; } else if (pocketed === 0) rotateTurn(next, players); return next; }
  outcome(state: GameState, players: GamePlayer[]): GameOutcome { const winner = typeof state.winnerId === 'string' ? state.winnerId : ''; return { finished: Boolean(state.finished), winnerIds: winner ? [winner] : [], loserIds: winner ? players.filter((p) => p.id !== winner).map((p) => p.id) : [], draw: false }; }
  botAction(): Action { return { type: 'strike', power: 65, pocketed: 1, queen: false }; }
}
